<?php

namespace Compte\Repository;

/**
 * MemberTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
