<?php

namespace Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RepositoryRole
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRole extends EntityRepository
{
}
